// Generated by CoffeeScript 1.7.1
(function() {
  var landing;

  landing = {
    recipient: {
      email: 'maxim.krivodaev@gmail.com',
      type: 'to'
    },
    email_api: {
      url: 'https://mandrillapp.com/api/1.0/',
      commands: {
        'send': 'messages/send.json'
      }
    },
    subject: 'Contact form',
    send_email: function(from, html) {
      var data, url;
      url = landing.email_api.url + landing.email_api.commands.send;
      data = {
        key: 'tvu6wJsFFNgYHCh9ce0SJw',
        message: {
          from_email: from,
          to: [landing.recipient],
          autotext: true,
          subject: landing.subject,
          html: html
        }
      };
      $.ajax({
        type: 'POST',
        dataType: 'jsonp',
        url: url,
        data: data
      }).done(function(r) {
        return console.log(r);
      }).error(function(e) {
        return console.log(e);
      });
      return landing.subject = 'Contact form';
    }
  };

  $(document).ready(function() {
    var contacts;
    contacts = $('#contacts');
    $('.btn-order').click(function() {
      landing.subject = 'Order form';
      contacts.find('#InputMessage').val(this.value);
      return contacts.modal('show');
    });
    return $('#sendContactForm').click(function() {
      var from, html;
      from = contacts.find('#InputEmail').val();
      html = contacts.find('#InputMessage').val();
      from = 'maxim.krivodaev@gmail.com';
      return landing.send_email(from, html);
    });
  });

}).call(this);

//# sourceMappingURL=scripts.map
